"""Add color column to containers

Revision ID: 6bf90a753d1a
Revises: ef27ec961563
Create Date: 2023-04-24 14:53:30.839064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf90a753d1a'
down_revision = 'ef27ec961563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(), nullable=True))

    with op.batch_alter_table('container_item', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container_item', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
