"""Add quantity on container-item relation, add identifier on container and item

Revision ID: ef27ec961563
Revises: 50f226f7f141
Create Date: 2023-03-31 15:47:51.664149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef27ec961563'
down_revision = '50f226f7f141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.String(), nullable=True))

    with op.batch_alter_table('container_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.alter_column('container_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('identifier')

    with op.batch_alter_table('container_item', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('container_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('quantity')
        batch_op.drop_column('id')

    with op.batch_alter_table('container', schema=None) as batch_op:
        batch_op.drop_column('identifier')

    # ### end Alembic commands ###
