name: "Sort-o-matic"
description: "Sort and find items in physical containers"
version: "0.0.1"
slug: "sort-o-matic"
panel_icon: mdi:server

init: false
startup: application

ingress: true


arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

